name: Deploy  react prod  

on:
  push:
    branches: [main]
jobs:
  deploy:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v2
        with:
          ref: main
      - name: deploy main boyslot prod
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.boyslot }}
          username: ${{ secrets.HOST }}
          key: ${{ secrets.SSHKEY_S}}
          port: ${{ secrets.PORT }}
          script: |
            pwd
            ./member.sh
